FROM python:3.7.1-alpine3.8

WORKDIR /usr/src/app
ADD requirements.txt src/main.py ./
RUN apk add -U gcc linux-headers musl-dev && \
    pip install -r requirements.txt && \
    apk del gcc linux-headers musl-dev

WORKDIR /etc/uwsgi
ADD cfg/uwsgi.ini .

USER root:root

CMD uwsgi --ini /etc/uwsgi/uwsgi.ini
