FROM python:3.7.1-alpine3.8

WORKDIR /etc/uwsgi
ADD cfg/uwsgi.ini .

WORKDIR /usr/src/app
ADD requirements.txt .
RUN apk add -U gcc linux-headers musl-dev && \
    pip install -r requirements.txt && \
    apk del gcc linux-headers musl-dev
ADD src/main.py ./
ADD src/ckb ./ckb

USER root:root
CMD uwsgi --ini /etc/uwsgi/uwsgi.ini
